=== yurigo/xmlon/pokemon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PokemonData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pokemon" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                            <xs:element name="Tipo" type="xs:string" maxOccurs="2"/>
                            <xs:element name="Habilidad" type="xs:string"/>
                            <xs:element name="Evoluciones" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Evolucion" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="ID" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="HP" type="xs:integer"/>
                            <xs:element name="Ataques">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Ataque" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Nombre" type="xs:string"/>
                                                    <xs:element name="Tipo" type="xs:string"/>
                                                    <xs:element name="DaÃ±o" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ID" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yurigo/xmlon/pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<PokemonData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pokemon.xsd">
    <Pokemon ID="1">
        <Nombre>Bulbasaur</Nombre>
        <Tipo>Planta</Tipo>
        <Tipo>Veneno</Tipo>
        <Habilidad>Espesura</Habilidad>
        <Evoluciones>
            <Evolucion ID="2">Ivysaur</Evolucion>
        </Evoluciones>
        <HP>45</HP>
        <Ataques>
            <Ataque>
                <Nombre>Latigazo</Nombre>
                <Tipo>Planta</Tipo>
                <Daño>45</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Drenadoras</Nombre>
                <Tipo>Planta</Tipo>
                <Daño>0</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="2">
        <Nombre>Ivysaur</Nombre>
        <Tipo>Planta</Tipo>
        <Tipo>Veneno</Tipo>
        <Habilidad>Espesura</Habilidad>
        <Evoluciones>
            <Evolucion ID="3">Venusaur</Evolucion>
        </Evoluciones>
        <HP>60</HP>
        <Ataques>
            <Ataque>
                <Nombre>Hoja Afilada</Nombre>
                <Tipo>Planta</Tipo>
                <Daño>55</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Rayo Solar</Nombre>
                <Tipo>Planta</Tipo>
                <Daño>120</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="3">
        <Nombre>Venusaur</Nombre>
        <Tipo>Planta</Tipo>
        <Tipo>Veneno</Tipo>
        <Habilidad>Espesura</Habilidad>
        <HP>80</HP>
        <Ataques>
            <Ataque>
                <Nombre>Rayo Solar</Nombre>
                <Tipo>Planta</Tipo>
                <Daño>120</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Terremoto</Nombre>
                <Tipo>Tierra</Tipo>
                <Daño>100</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="4">
        <Nombre>Charmander</Nombre>
        <Tipo>Fuego</Tipo>
        <Habilidad>Mar Llamas</Habilidad>
        <Evoluciones>
            <Evolucion ID="5">Charmeleon</Evolucion>
        </Evoluciones>
        <HP>39</HP>
        <Ataques>
            <Ataque>
                <Nombre>Ascuas</Nombre>
                <Tipo>Fuego</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Garra Dragón</Nombre>
                <Tipo>Dragón</Tipo>
                <Daño>80</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="5">
        <Nombre>Charmeleon</Nombre>
        <Tipo>Fuego</Tipo>
        <Habilidad>Mar Llamas</Habilidad>
        <Evoluciones>
            <Evolucion ID="6">Charizard</Evolucion>
        </Evoluciones>
        <HP>58</HP>
        <Ataques>
            <Ataque>
                <Nombre>Lanzallamas</Nombre>
                <Tipo>Fuego</Tipo>
                <Daño>90</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Colmillo Ígneo</Nombre>
                <Tipo>Fuego</Tipo>
                <Daño>65</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>

    <Pokemon ID="6">
        <Nombre>Charizard</Nombre>
        <Tipo>Fuego</Tipo>
        <Tipo>Volador</Tipo>
        <Habilidad>Mar Llamas</Habilidad>
        <HP>78</HP>
        <Ataques>
            <Ataque>
                <Nombre>Lanzallamas</Nombre>
                <Tipo>Fuego</Tipo>
                <Daño>90</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Ataque Ala</Nombre>
                <Tipo>Volador</Tipo>
                <Daño>60</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>

    <Pokemon ID="7">
        <Nombre>Squirtle</Nombre>
        <Tipo>Agua</Tipo>
        <Habilidad>Torrente</Habilidad>
        <Evoluciones>
            <Evolucion ID="8">Wartortle</Evolucion>
        </Evoluciones>
        <HP>44</HP>
        <Ataques>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Pistola Agua</Nombre>
                <Tipo>Agua</Tipo>
                <Daño>40</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="8">
        <Nombre>Wartortle</Nombre>
        <Tipo>Agua</Tipo>
        <Habilidad>Torrente</Habilidad>
        <Evoluciones>
            <Evolucion ID="9">Blastoise</Evolucion>
        </Evoluciones>
        <HP>59</HP>
        <Ataques>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Hidrobomba</Nombre>
                <Tipo>Agua</Tipo>
                <Daño>110</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="9">
        <Nombre>Blastoise</Nombre>
        <Tipo>Agua</Tipo>
        <Habilidad>Torrente</Habilidad>
        <HP>79</HP>
        <Ataques>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Hidrobomba</Nombre>
                <Tipo>Agua</Tipo>
                <Daño>110</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="10">
        <Nombre>Caterpie</Nombre>
        <Tipo>Bicho</Tipo>
        <Habilidad>Polvo Escudo</Habilidad>
        <Evoluciones>
            <Evolucion ID="11">Metapod</Evolucion>
        </Evoluciones>
        <HP>45</HP>
        <Ataques>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Drenadoras</Nombre>
                <Tipo>Bicho</Tipo>
                <Daño>20</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="11">
        <Nombre>Metapod</Nombre>
        <Tipo>Bicho</Tipo>
        <Habilidad>Mudar</Habilidad>
        <Evoluciones>
            <Evolucion ID="12">Butterfree</Evolucion>
        </Evoluciones>
        <HP>50</HP>
        <Ataques>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Drenadoras</Nombre>
                <Tipo>Bicho</Tipo>
                <Daño>20</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="12">
        <Nombre>Butterfree</Nombre>
        <Tipo>Bicho</Tipo>
        <Tipo>Volador</Tipo>
        <Habilidad>Ojo Compuesto</Habilidad>
        <HP>60</HP>
        <Ataques>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Confusión</Nombre>
                <Tipo>Psíquico</Tipo>
                <Daño>50</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>

    <Pokemon ID="13">
        <Nombre>Weedle</Nombre>
        <Tipo>Bicho</Tipo>
        <Tipo>Veneno</Tipo>
        <Habilidad>Polvo Escudo</Habilidad>
        <Evoluciones>
            <Evolucion ID="14">Kakuna</Evolucion>
        </Evoluciones>
        <HP>40</HP>
        <Ataques>
            <Ataque>
                <Nombre>Picotazo Venenoso</Nombre>
                <Tipo>Veneno</Tipo>
                <Daño>15</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="14">
        <Nombre>Kakuna</Nombre>
        <Tipo>Bicho</Tipo>
        <Tipo>Veneno</Tipo>
        <Habilidad>Mudar</Habilidad>
        <Evoluciones>
            <Evolucion ID="15">Beedrill</Evolucion>
        </Evoluciones>
        <HP>45</HP>
        <Ataques>
            <Ataque>
                <Nombre>Picotazo Venenoso</Nombre>
                <Tipo>Veneno</Tipo>
                <Daño>15</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Endurecer</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>0</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="15">
        <Nombre>Beedrill</Nombre>
        <Tipo>Bicho</Tipo>
        <Tipo>Veneno</Tipo>
        <Habilidad>Enjambre</Habilidad>
        <HP>65</HP>
        <Ataques>
            <Ataque>
                <Nombre>Picotazo Venenoso</Nombre>
                <Tipo>Veneno</Tipo>
                <Daño>35</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Furia</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>20</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="16">
        <Nombre>Pidgey</Nombre>
        <Tipo>Normal</Tipo>
        <Tipo>Volador</Tipo>
        <Habilidad>Vista Lince</Habilidad>
        <Evoluciones>
            <Evolucion ID="17">Pidgeotto</Evolucion>
        </Evoluciones>
        <HP>40</HP>
        <Ataques>
            <Ataque>
                <Nombre>Placaje</Nombre>
                <Tipo>Normal</Tipo>
                <Daño>40</Daño>
            </Ataque>
            <Ataque>
                <Nombre>Remolino</Nombre>
                <Tipo>Volador</Tipo>
                <Daño>35</Daño>
            </Ataque>
        </Ataques>
    </Pokemon>
    <Pokemon ID="17">
        <Nombre>Pidgeotto</Nombre>
        <Tipo>Normal</Tipo>
